
globalVariables(
  c(
    "cas_confirmes",
    "confirmed",
    "date",
    "dead",
    "deces",
    "depistes",
    "desc",
    "france_country",
    "france_regional",
    "granularite",
    "gueris",
    "hospitalises",
    "hospitalized",
    "icu",
    "maille_code",
    "maille_nom",
    "mutate_if",
    "reanimation",
    "recovered",
    "region_code",
    "region_name",
    "region_type",
    "source_type",
    "source_url"
  )
)
